import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Shubham Lad | Portfolio ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=panchang@200,300,400,500,600,700,800,1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >{children}</body>
    </html>
  );
}
